export class Usager {
    constructor(public id: String = null,
                public nom?: String,
                public prenoms?: String,
                public date_naiss?: String,
                public lieu_naiss?: String,
                public nationalite?: String,
                public photo?: any,
                public adresse?: String,
                public telephone?: String,
                public email?: String,
                public fonction?: String,
                public num_piece_identite?: String,
                public num_carte_professionelle?: String,
                public num_certificat_prise_service?: String,
                public type_acces?: String,
                public temps_acces?: String,
                public actif?: boolean,
                public date_ajout?: String,
                public statut?: String,
                public structure_id?: String,
                public badge_id?: String,
                public badge_type_id?: String,
                public zone_id?: String,
                public created_at?: String,
                public updated_at?: String,
    ) {}
}
